services:
  a2a_bake_off_agent:
    build:
      context: a2a_bake_off_agent/        
      dockerfile: Dockerfile 
    ports:
      - "8000:8080"
    env_file:
      - ./compose.env

  a2a_cymbal_bank_agent:
    build:
      context: a2a_cymbal_bank_agent/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./compose.env

  a2a_ui_tool:
    build:
      context: a2a_ui_tool/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    env_file:
      - ./compose.env