services:
  backend:
    build:
      context: backend/        
      dockerfile: Dockerfile 
    ports:
      - "8081:8080"       
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./compose.env